name: Deploy

on:
  push:
    branches:
      - master
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Deploy to staging
        if: github.ref == 'refs/heads/qa'
        with:
          heroku_app_name: ${{secrets.HEROKU_STG_APP_NAME}}

      - name: Deploy to production
        if: github.ref == 'refs/heads/master'
        with:
          heroku_app_name: ${{secrets.HEROKU_PRD_APP_NAME}}
